### ISSUE TITLE
Missing car models

### ISSUE THREAD

**Issue by Tbarowski** [ApolloScapeAuto/dataset-api#13]
I'm trying to run the sample from the readme and I'm getting an error due to missing models. I double checked the download, but could not manage to find certain models.

```
> python render_car_instances.py --split='sample_data' --image_name='180116_053951969_Camera_5' --data_dir='../apolloscape/3d_car_instance_sample/'
Test visualizer
INFO:root:loading 79 car models
Traceback (most recent call last):
  File "render_car_instances.py", line 298, in <module>
    visualizer.load_car_models()
  File "render_car_instances.py", line 59, in load_car_models
    with open(car_model) as f:
IOError: [Errno 2] No such file or directory: '../apolloscape/3d_car_instance_sample/car_models//biaozhi-3008.pkl' 
```

Following models are missing:
biaozhi-3008
bieke-yinglang-XT.pkl
biyadi-2x-F0.pkl
changanbenben.pkl
jilixiongmao-2015.pkl
lingmu-aotuo-2009.pkl
lingmu-SX4-2012.pkl
dazhongmaiteng.pkl

**Comment by PeiliangLi** [comment]
same issue

**Comment by Tbarowski** [comment]
@PeiliangLi see https://github.com/ApolloScapeAuto/dataset-api/issues/1#issuecomment-455473902

**Comment by XibinSong** [comment]
@Tbarowski @PeiliangLi , The car models are in the folder of 3d_car_instance_sample.tar.gz, it can be downloaded from 3d car instance website.

**Comment by schen119** [comment]
@XibinSong the 3d_car_instance_sample.tar.gz now still missed some car models defined in car_models.py.
