### ISSUE TITLE
Can't get attribute 'CHJ_tiny_obj' on <module 'objloader'

### ISSUE THREAD

**Issue by ying-tiger-cai** [ApolloScapeAuto/dataset-api#33]
When running car_instance/demo.ipynb, I met the following error. Is there any clue to fix this? Many thanks!

----> 8 visualizer.load_car_models()
      9 image_vis, mask, depth = visualizer.showAnn(setting.image_name)

~/Workspaces/apollocar3d/dataset-api/car_instance/render_car_instances.py in load_car_models(self)
     62             print(car_model)
     63             with open(car_model, 'rb') as f:
---> 64                 self.car_models[model.name] = pkl.load(f)
     65                 # fix the inconsistency between obj and pkl
     66                 self.car_models[model.name]['vertices'][:, [0, 1]] *= -1

AttributeError: Can't get attribute 'CHJ_tiny_obj' on <module 'objloader' from '/home/ark/Workspaces/apollocar3d/dataset-api/car_instance/objloader.py'>

**Comment by RuanYue** [comment]
The same problem happens to me. And I have no clue how to solve it. Is there anyone who could shed some light on it?

**Comment by RuanYue** [comment]
The same problem happens to me. And I have no clue how to solve it. Is there anyone who could shed some light on it?

**Comment by zozobozo** [comment]
take a look in these kaggle links [here](https://www.kaggle.com/c/pku-autonomous-driving/discussion/113888) and [here](https://www.kaggle.com/ebouteillon/load-a-3d-car-model); the authors reloaded the models as json files. 

It's a shame nobody bothers to update this too.
please don't close this issue until they update the json files here.

**Comment by cch2016** [comment]
> When running car_instance/demo.ipynb, I met the following error. Is there any clue to fix this? Many thanks!
> 
> ----> 8 visualizer.load_car_models()
> 9 image_vis, mask, depth = visualizer.showAnn(setting.image_name)
> 
> ~/Workspaces/apollocar3d/dataset-api/car_instance/render_car_instances.py in load_car_models(self)
> 62 print(car_model)
> 63 with open(car_model, 'rb') as f:
> ---> 64 self.car_models[model.name] = pkl.load(f)
> 65 # fix the inconsistency between obj and pkl
> 66 self.car_models[model.name]['vertices'][:, [0, 1]] *= -1
> 
> AttributeError: Can't get attribute 'CHJ_tiny_obj' on <module 'objloader' from '/home/ark/Workspaces/apollocar3d/dataset-api/car_instance/objloader.py'>

When I running 'render_car_instance.py ',I have the following error":
------------------------------------------------------------------------------------------------------------
Test visualizer
INFO:root:loading 79 car models
car_model: /home/cch/Documents/apolloscape/3d_car_instance_sample/car_models/baojun-310-2017.pkl
Traceback (most recent call last):
  File "render_car_instances.py", line 302, in <module>
    visualizer.load_car_models()
  File "render_car_instances.py", line 63, in load_car_models
    self.car_models[model.name] = pkl.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1075, in load_inst
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named objloader
----------------------------------------------------------------------------------------------------
I see in you ''car_instance'' folder , there is ''objloader.py'' file , but I don't and in author's code isn't。

**Comment by xu-jiusi** [comment]
解决了吗，我也碰到了这个问题
